version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    assignees:
      - "ascopes"
    labels:
      - "ci"

  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    assignees:
      - "ascopes"
    labels:
      - "maven"
